- name: Deploy api server
  hosts: api
  become: yes
  environment:
    GOPATH: /usr/local/gopath
  pre_tasks:
    - name: Make sure log directory exists
      file: recurse=yes dest=/var/log/sole force=no owner={{ ansible_user }} group={{ ansible_user }} mode=0755 state=directory

    - name: Remove solebtc source code first
      file: path=/usr/local/gopath/src/github.com/freeusd/solebtc state=absent
    - name: Build solebtc
      command: go get -u github.com/freeusd/solebtc
    - name: move solebtc to /usr/local/bin/sole
      command: mv solebtc /usr/local/bin/sole chdir=/usr/local/gopath/bin

    - name: Build goose for db migration
      command: go get bitbucket.org/liamstask/goose/cmd/goose
    - name: move goose to /usr/local/bin/goose
      command: mv goose /usr/local/bin/goose chdir=/usr/local/gopath/bin

    - name: Prepare configuration file
      template: src=sole.conf.j2 dest=/etc/supervisor/conf.d/sole.conf
  tasks:
    - name: Migrate database
      command: goose -env production up chdir=/usr/local/gopath/src/github.com/freeusd/solebtc
      
    - name: Supervisorctl restart sole
      supervisorctl: name=sole state=restarted

- name: Deploy admin panel
  hosts: api
  become: yes
  pre_tasks:
    - name: Make sure log directory exists
      file: recurse=yes dest=/var/log/sole-admin force=no owner={{ ansible_user }} group={{ ansible_user }} mode=0755 state=directory
    - name: Remove sole-admin source code first
      file: path=/usr/local/share/sole-admin state=absent
    - name: Git clone sole-admin
      git: repo=https://github.com/freeusd/solebtc-admin.git dest=/usr/local/share/sole-admin
    - name: Build sole-admin
      command: npm run build chdir=/usr/local/share/sole-admin
    - name: Prepare sole-admin users.json
      template: src=sole-admin-users.conf.j2 dest=/usr/local/share/sole-admin/config/users.json
    - name: Prepare sole-admin supervisor configuration file
      template: src=sole-admin.conf.j2 dest=/etc/supervisor/conf.d/sole-admin.conf
    - name: Make sole-admin belongs to current user
      file: path=/usr/local/share/sole-admin recurse=yes owner={{ ansible_user }} group={{ ansible_user }} mode=0755 state=directory
  tasks:
    - name: Supervisorctl restart sole-admin
      supervisorctl: name=sole-admin state=restarted
