- name: Deploy web
  hosts: api
  become: yes
  tasks:
    - name: Make sure web dists exists
      file:
        path: /usr/local/share/sole-web/dists
        state: directory
        mode: 0755
        recurse: yes

    - name: Download web
      get_url:
        url: "{{ web_dist_url }}"
        dest: /usr/local/share/sole-web/dists/dist.tar.gz
        mode: 0755
        force: yes
        backup: yes

    - name: Remove web root
      file:
        path: /usr/local/share/sole-web/dist
        state: absent
        mode: 0755

    - name: Extract web dist
      command: tar xvf dist.tar.gz -C /usr/local/share/sole-web/ chdir=/usr/local/share/sole-web/dists
