- name: Deploy api server
  hosts: api
  become: yes
  environment:
    GOPATH: /usr/local/gopath
  pre_tasks:
    - name: Make sure log directory exists
      file: recurse=yes dest=/var/log/sole force=no owner={{ ansible_user }} group={{ ansible_user }} mode=0755 state=directory

    - name: Download geo database
      get_url:
        url: http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
        dest: /opt/GeoLite2-City.mmdb.gz
    - name: Unarchive geo database
      command: gzip -d -f GeoLite2-City.mmdb.gz chdir=/opt

    - name: Remove sole-server source code first
      file: path=/usr/local/gopath/src/github.com/solefaucet/sole-server state=absent
    - name: Clone sole-server
      git:
        repo: https://github.com/solefaucet/sole-server.git
        dest: /usr/local/gopath/src/github.com/solefaucet/sole-server
    - name: Build sole-server
      shell: "go build -ldflags \"-X main.goVersion=`go version | grep -o 'go[0-9|.]\\+'` -X main.buildTime=`date '+%Y-%m-%d_%I:%M:%S%p'` -X main.gitCommit=`git rev-parse --short HEAD`\" -o /usr/local/bin/sole chdir=/usr/local/gopath/src/github.com/solefaucet/sole-server"

    - name: Build goose for db migration
      command: go get bitbucket.org/liamstask/goose/cmd/goose
    - name: move goose to /usr/local/bin/goose
      command: mv goose /usr/local/bin/goose chdir=/usr/local/gopath/bin

    - name: Prepare configuration file
      template: src=sole.conf.j2 dest=/etc/supervisor/conf.d/sole.conf
  tasks:
    - name: Supervisorctl stop sole
      supervisorctl: name=sole state=stopped

    - name: Migrate database
      command: goose -env production up chdir=/usr/local/gopath/src/github.com/solefaucet/sole-server
      
    - name: Supervisorctl start sole
      supervisorctl: name=sole state=started
