- name: Tweak system
  hosts: all
  become: yes
  roles:
    - kunik.system-limits
    - mrlesmithjr.network-tweaks

- name: Setup ntp cronjob
  hosts: all
  become: yes
  tasks:
    - cron:
        name: Adjust time every day
        special_time: daily
        job: ntpdate ntp.ubuntu.com

- name: Install golang
  hosts: api
  become: yes
  roles:
    - role: azavea.golang
      golang_version: 1.6
      golang_os: linux
      golang_arch: amd64
      golang_path: /usr/local/gopath

- name: Install git
  hosts: all
  become: true
  roles:
    - role: geerlingguy.git
      workspace: /opt
      git_version: 2.7.0
      git_install_from_source: true

- name: Install supervisor
  hosts: api 
  become: yes
  roles:
    - pcextreme.supervisor

- name: Install MySQL5.7
  hosts: api 
  become: yes
  vars_files:
    - vars/mysql.yml
  pre_tasks:
    - name: Add MySQL repository key
      apt_key: url=http://repo.mysql.com/RPM-GPG-KEY-mysql state=present
    - name: Add MySQL-5.7
      apt_repository: repo='deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7' state=present
    - name: Add MySQL-apt-config
      apt_repository: repo='deb http://repo.mysql.com/apt/ubuntu/ trusty mysql-apt-config' state=present
    - name: Add MySQL-5.7 src
      apt_repository: repo='deb-src http://repo.mysql.com/apt/ubuntu/ trusty mysql-5.7' state=present
  roles:
      - geerlingguy.mysql

- name: Issue letsencrypt ssl cert 
  hosts: api 
  become: yes
  roles:
    - role: thefinn93.letsencrypt
      letsencrypt_email: nanohugh@gmail.com
      letsencrypt_cert_domains:
        - "{{ ansible_host }}"
      letsencrypt_rsa_key_size: 2048
      letsencrypt_renewal_frequency:
        day: "*"
        hour: 0
        minute: 0
      letsencrypt_renewal_command_args: '--renew-hook "service nginx reload"'

- name: Initialize nginx 
  hosts: api 
  become: yes
  vars:
    nginx_official_repo: True 
  roles:
    - role: jdauphant.nginx
      nginx_error_log_level: info
      nginx_sites:
        sole.80:
          - listen 80
          - server_name {{ ansible_host }}
          - return 301 https://$host$request_uri
        sole.443:
          - listen 443 ssl
          - server_name {{ ansible_host }}
          - ssl_ciphers 'kEECDH+ECDSA+AES128 kEECDH+ECDSA+AES256 kEECDH+AES128 kEECDH+AES256 kEDH+AES128 kEDH+AES256 DES-CBC3-SHA +SHA !aNULL !eNULL !LOW !kECDH !DSS !MD5 !EXP !PSK !SRP !CAMELLIA !SEED'
          - add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains;'
          - ssl_stapling on
          - ssl_certificate /etc/letsencrypt/live/{{ ansible_host }}/cert.pem
          - ssl_certificate_key /etc/letsencrypt/live/{{ ansible_host }}/privkey.pem
          - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
          - ssl_prefer_server_ciphers on
          - ssl_session_cache shared:SSL:10m
          - ssl_session_timeout 10m
          - |
            location /api/ {
              proxy_pass http://localhost:8749/;
              proxy_set_header Host $host;
              proxy_set_header X-Real-IP $remote_addr;

              # websocket
              proxy_http_version 1.1;
              proxy_set_header Upgrade $http_upgrade;
              proxy_set_header Connection "upgrade";
            }
          - root /usr/share/nginx/html
          - |
            location ~ (?:.+\/)((?:.+)\.(?:.+)) {
              try_files $uri /$1 /css/$1 =404;
            }
          - |
            location / {
              try_files $uri /index.html;
            }

- name: Initialize crypto coin daemon
  hosts: api
  become: yes
  tasks:
    - name: Copy coind
      get_url: 
        url: "{{ wallet_url }}"
        dest: /usr/bin/coind
        mode: 0755
        force: no
    - name: Copy coind conf
      copy:
        src: coind.conf
        dest: /etc/coind.conf
        mode: 0755
    - name: Create coind data directory
      file: 
        path: /var/lib/coind
        state: directory
        mode: 0755
    - name: Start coind on reboot
      cron:
        name: Start coind on reboot
        special_time: reboot
        job: /usr/bin/coind -daemon -conf=/etc/coind.conf -datadir=/var/lib/coind -pid=/var/run/coind.pid

- name: Install graylog-server
  hosts: log
  become: yes 
  pre_tasks:
    - name: Add java 8 repo
      apt_repository: repo='ppa:openjdk-r/ppa'
  roles:
    - role: geerlingguy.elasticsearch
      java_packages:
        - openjdk-8-jdk
    - role: greendayonfire.mongodb
    - role: graylog
    - role: jdauphant.nginx
      nginx_official_repo: True 
      nginx_error_log_level: info
      nginx_sites:
        graylog:
          - listen 80
          - server_name log.solebtc.com
          - |
            location / {
              proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header    Host $http_host;
              proxy_set_header    X-Graylog-Server-URL http://log.solebtc.com/api;
              proxy_pass          http://127.0.0.1:9000;
            }
          - |
            location /api/ {
              proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
              proxy_set_header    Host $http_host;
              proxy_pass          http://127.0.0.1:12900/;
            }

- name: Restart machine
  hosts: all
  become: true
  tasks:
    - name: Reboot
      shell: sleep 2 && shutdown -r now "Reboot triggered by Ansible"
      async: 1
      poll: 0
      ignore_errors: true 
